### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by Sytten** [c410-f3r/oapth#41]
Hi there!
I was just wondering if the project is still alive and what is missing to do a release on crates.
I am looking to switch my current diesel migrations to something more universal and your library seems very well made.
Thanks

**Comment by Sytten** [comment]
Make sense thanks for the answer.
Do you think it would be possible for me to add migrations that are in rust? I have some use case that are more complex than just SQL.

**Comment by c410-f3r** [comment]
Do you mean a Rust-based DSL for migrations like https://book.cakephp.org/phinx/0/en/migrations.html#creating-a-table? If so, then no. Only SQL is supported and in my experience, DSL is not a thing when dealing with different databases with different syntaxes.

If the migrations are embedded in a Rust program to easily deploy an application, then yes, it is possible to add migration that are in Rust. For example, take a look at https://github.com/c410-f3r/oapth/blob/master/oapth/tests/embed-migrations.rs

**Comment by Sytten** [comment]
Yeah the migrations are embedded, so I should be able to mix and match with migrations written in rust. I will give it a go!
