### ISSUE TITLE
Meta issue for `clean` method

### ISSUE THREAD

**Issue by c410-f3r** [c410-f3r/oapth#5]
## Description

This issue gathers all remaining missing aspects of `clean` and also serves as a general tutorial.

The `clean` method tries to clean all objects of a database, including user created schemas, but is very tricky to implement for all databases. To make life easier, the current implementation of `flyway` is going to be used as a development reference (hope the flyway guys don't mind).

#### 1. Choose a database and a missing target

For example, let's pick PostgreSQL to see what `flyway` does and what `oapth` currently can do:

https://github.com/flyway/flyway/blob/e2ffad5790f484b434a761f23e431ba8e3e232f8/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLSchema.java#L81

https://github.com/c410-f3r/oapth/blob/ff8c02d661224bbacdda557a7120a860348c762f/oapth/src/fixed_sql_commands/pg.rs#L20

By looking into both projects, it is possible to see that `oapth` doesn't remove sequences, so let's implement it.

#### 2. Implementation

Let's create the function that lists all sequences (don't forget to link and credit the original `flyway` source):

```sql
// https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/database/postgresql/PostgreSQLSchema.java
#[oapth_macros::dev_tools_]
#[inline]
pub async fn sequences<B>(back_end: &mut B, schema: &str) -> crate::Result<Vec<String>>
where
  B: crate::BackEnd
{
  let mut buffer = ArrayString::<[u8; 128]>::new();
  buffer.write_fmt(format_args!(
    "SELECT sequence_name AS generic_column FROM information_schema.sequences WHERE sequence_schema = '{schema}'",
    schema = schema
  ))?;
  Ok(back_end.query_string(&buffer).await?)
}
```

And insert the drop statement within the `clean` function:

```rust
for sequence in sequences(back_end, "public").await? {
  buffer.write_fmt(format_args!("DROP SEQUENCE {};", domain))?;
}
```

#### 3. Testing

Since this is a specific behavior of `PostgreSQL`, we are going to include some code into the already existing `clean_drops_all_objs` test:

https://github.com/c410-f3r/oapth/blob/ff8c02d661224bbacdda557a7120a860348c762f/oapth/src/integration_tests/db/pg.rs#L2

```rust
...

c.back_end.execute("CREATE SEQUENCE serial START 101;").await.unwrap();

...

assert_eq!(crate::fixed_sql_commands::pg::sequences(&mut c.back_end).await.unwrap().len(), 1);

...

c.clean().await.unwrap();

...

assert_eq!(crate::fixed_sql_commands::pg::sequences(&mut c.back_end).await.unwrap().len(), 0);

...
```

Now it is only a matter of running the test. Go to the project root directory and type `./scripts/integration-tests-pg.sh` to run your shinny new test through the `diesel`, `tokio_postgres` and `sqlx` database bridges.

Check out https://github.com/c410-f3r/oapth/blob/master/CONTRIBUTING.md for more information.

#### MS-SQL

- [ ] #20
- [ ] #21 
- [ ] #22 
- [ ] #23 
- [ ] #24

#### MySql

- [ ] #15 
- [ ] #16 
- [ ] #17 
- [ ] #18 

#### PostgreSQL

- [x] #6
- [x] #7
- [x] #8

#### SQLite

- [ ] #19

**Comment by zacck** [comment]
Hi, I'm keen to work through this, do think it's ok for someone relatively new to rust to try this?

**Comment by c410-f3r** [comment]
@zacck For learning purposes, it is totally OK! Feel free to ask any question in this thread

**Comment by zacck** [comment]
Will  leave a few questions in a few hours when I push on this ?

**Comment by zacck** [comment]
@c410-f3r  so the example you have laid out seems to fix the implementation for Postgres, however your explanation seems to allude to one doing this for all the databases. I would like to know what is needed, i.e is it just Postgres implementations or all the databases... thank you so much!

**Comment by c410-f3r** [comment]
@zacck Indeed! This issue is a tracker for all databases but the implementation itself is a bit laborious. I will try to create more issues to fully cover all remaining aspects for mssql, mysql and sqlite.

**Comment by zacck** [comment]
Oh I  see! well I am keen to follow along and try implement the work, I think this is exactly what I need to grow into rust
