### ISSUE TITLE
[PostgreSQL] `clean` should remove views

### ISSUE THREAD

**Issue by c410-f3r** [c410-f3r/oapth#8]
See #5

**Comment by zacck** [comment]
@c410-f3r Going to try implementing this one, shall we use the flyaway implementation as well?

**Comment by c410-f3r** [comment]
@zacck Sure! Feel free to work on this issue.

You can create your own view query selection but yeah, it is probably easier to just look into the `flyway` implementation, something like:

```sql
SELECT relname AS generic_column FROM pg_catalog.pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind = 'm' AND n.nspname = {schema}
```

**Comment by zacck** [comment]
@c410-f3r  I can't seem to understand the SQL operation above would you care to explain it?

**Comment by zacck** [comment]
Aha I see, this searches for views which we can then drop!
